import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
  'FETCHING_ABOUT_US',
  'FETCH_ABOUT_US_SUCCESS',
  'FETCH_ABOUT_US_ERROR',
  'FETCHING_YOUTUBE_VIDEO',
  'FETCH_YOUTUBE_VIDEO_SUCCESS',
  'FETCH_YOUTUBE_VIDEO_ERROR',
  'FETCHING_CONTACT_US',
  'FETCH_CONTACT_US_SUCCESS',
  'FETCH_CONTACT_US_ERROR'
]);
